export const ROBOT_DEVICE_NAME = 'ESP_ROBOT';

export const BLUETOOTH_DEFAULT_CONFIG = {
  SCAN_TIMEOUT: 10000,
  CONNECT_TIMEOUT: 10000,
  RESCAN_DELAY: 3000,
  MAX_RESCAN_ATTEMPTS: 5,
  MTU_ANDROID: 247,
  PROTOCOL_RESPONSE_TIMEOUT: 3000,
};

export const BLUETOOTH_UUIDS = {
  SERVICE_UUID: '00FF',
  PROTOCOL_IO: 'FF01',
  SERVO_CTRL: 'FF01',
  PROVISIONING_CTRL: 'FF01',
  ACTION_CTRL: 'FF01',
  STATUS: 'FF01',
  DEVICE_INFO_SERVICE: '180A',
  MANUFACTURER_NAME: '2A29',
  FIRMWARE_REVISION: '2A26',
  HARDWARE_REVISION: '2A27',
  SERIAL_NUMBER: '2A25',
} as const;

export const SERVO_CONFIG = {
  SERVO_X: 0,
  SERVO_Y: 1,
  AXIS_X_DEFAULT_ANGLE: 90,
  AXIS_Y_DEFAULT_ANGLE: 90,
  ANGLE_MIN: 0,
  ANGLE_MAX: 180,
  STEP_DEGREES: 10,
  STEP_INTERVAL_MS: 120,
} as const;
